### PR TITLE
Use master and mafia.

### PR DESCRIPTION
**Pull request by tmcgilchrist**

### CODE REVIEW

**Comment by charleso** [comment]
:+1:

**Comment by charleso** [comment]
I'm assuming you'll update anatomy-ambiata in a sec too

**Comment by tmcgilchrist** [comment]
Doing that right now.

**Comment by tmcgilchrist** [comment]
https://github.com/ambiata/anatomy-ambiata/pull/108

**Comment by nhibberd** [comment]
:+1:

**Comment by nhibberd** [comment]
Need to remove the cabal file as well

**Pull request merged**
